---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry
  namespace: pete-bot
spec:
  encryptedData:
    .dockerconfigjson: AgBrn3tLaJEif/T8LrjMpX2bHZlN6iz4+XQbWsZPtXL0ZssUOwtGizyMi+uUJ3vTQowD1r/vrFhgYA9ecrXgtdZA8frLJscdUwOC1Aq7oUiZM/LqaPS/raQOKcrjaF+4Gubqth67jLhdcXf9gqn1GrVky0MspDLi3RXhu/rbMBg4WSm7azkfO9N1ahHAXcC3bjN10ekLB0EckvQMJa+VtJZ36rJq8kjv9+mVQwH/Id5sS61kU003WxurQ3/fTre3UXpiWXmYftVYP0hQscZVNxVnjscuXJI1EsWDuBALLxKPecjmImR+QpZrqlJuiLroonQMAfSwhR2P5lIIbltCMqvyZ70diUUM+3FExnKJXudkyzQrdU13+4dBC6IXhmDs80nWWc2mwJgCdQEFeYvFPXlwRyMwhrvovPdI4FDHhDepjnMbKlDppm5oSJE5Aah4gCP/g4FKhkL6jnxfxrXrTAnHOSZOC8aqg7X03fUZ8Sz5UDFkYPGyFX97OwekCvEJidKH/OF/9g4VKRmrmAXlSk45deG7TiZfiLYtWL/HIwgP7cNGNteBVyv3F5LdXBsK48aIFY3XQOZsKOOl2FXNXV/k2m/2eObsKFqMQkbxP20S6ZyJNo5V9OYEBzUhJuFlxa8gaQcUw510vh2fikI5GJZwememJ13AAWkh4Tg+8YZuuWyscqPmKOgqkja1jkivhVhNnRoU2EgiMkftJ7MIrx64J0LyFzdiuRPX9fQbcyGwuDtKOybBIHzPpst6K3lafkYBdq9MXNRbJR+eZhey3mFBi6mDLyItVo5NriRMTKr38JzbhnxwN41i+0hZj+xtBV2eVb3taDBs310/7CY3bAF3jTKOTJsWTZkVrb/tcA==
  template:
    metadata:
      name: nexus-registry
      namespace: pete-bot
    type: kubernetes.io/dockerconfigjson
