apiVersion: v1
kind: Service
metadata:
  name: pete-bot-metrics
  namespace: pete-bot
  labels:
    app: pete-bot
    app.kubernetes.io/name: pete-bot
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: pete-bot
    app.kubernetes.io/component: bot
