apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pete-bot
resources:
- ../../base
# Use labels with includeSelectors: false to avoid breaking external services
labels:
- pairs:
    environment: prod
  includeSelectors: false
images:
- name: docker.toastedbytes.com/pete-bot
  digest: sha256:9aa1edd37a951d54aef874c0c1e4ea7b79422dcde2653660945ffc49d9053441
